// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: MyWota

#ifndef UI_OPERATIONALSCREEN_H
#define UI_OPERATIONALSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_operationalScreen
extern void ui_operationalScreen_screen_init(void);
extern void ui_operationalScreen_screen_destroy(void);
extern lv_obj_t * ui_operationalScreen;
extern lv_obj_t * ui_totalRemainingBar;
extern lv_obj_t * ui_levelColourIndicator;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_cardRemaining;
extern lv_obj_t * ui_ledIndicator;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_flowRateSensor;
extern lv_obj_t * ui_buttonState;
extern lv_obj_t * ui_customerID;
extern lv_obj_t * ui_cardErrorStatus;
// CUSTOM VARIABLES
extern lv_obj_t * uic_totalRemainingBar;
extern lv_obj_t * uic_levelColourIndicator;
extern lv_obj_t * uic_cardRemaining;
extern lv_obj_t * uic_ledIndicator;
extern lv_obj_t * uic_flowRateSensor;
extern lv_obj_t * uic_buttonState;
extern lv_obj_t * uic_customerID;
extern lv_obj_t * uic_cardErrorStatus;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

