// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: MyWota

#include "../ui.h"

lv_obj_t * uic_cardErrorStatus;
lv_obj_t * uic_customerID;
lv_obj_t * uic_buttonState;
lv_obj_t * uic_flowRateSensor;
lv_obj_t * uic_ledIndicator;
lv_obj_t * uic_cardRemaining;
lv_obj_t * uic_levelColourIndicator;
lv_obj_t * uic_totalRemainingBar;
lv_obj_t * ui_operationalScreen = NULL;
lv_obj_t * ui_totalRemainingBar = NULL;
lv_obj_t * ui_levelColourIndicator = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_cardRemaining = NULL;
lv_obj_t * ui_ledIndicator = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_flowRateSensor = NULL;
lv_obj_t * ui_buttonState = NULL;
lv_obj_t * ui_customerID = NULL;
lv_obj_t * ui_cardErrorStatus = NULL;
// event funtions

// build funtions

void ui_operationalScreen_screen_init(void)
{
    ui_operationalScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_operationalScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_operationalScreen, lv_color_hex(0xFFFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_operationalScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_operationalScreen, lv_color_hex(0x081E4C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_operationalScreen, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_operationalScreen, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_operationalScreen, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_totalRemainingBar = lv_bar_create(ui_operationalScreen);
    lv_bar_set_value(ui_totalRemainingBar, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_totalRemainingBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_totalRemainingBar, 151);
    lv_obj_set_height(ui_totalRemainingBar, 155);
    lv_obj_set_x(ui_totalRemainingBar, 2);
    lv_obj_set_y(ui_totalRemainingBar, 7);
    lv_obj_set_align(ui_totalRemainingBar, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_totalRemainingBar,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_totalRemainingBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_totalRemainingBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_totalRemainingBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_totalRemainingBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_totalRemainingBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_totalRemainingBar, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_totalRemainingBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_totalRemainingBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_totalRemainingBar, lv_color_hex(0x293C94), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_totalRemainingBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_totalRemainingBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_totalRemainingBar,
                                                                                                        lv_obj_get_style_pad_right(ui_totalRemainingBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_levelColourIndicator = lv_obj_create(ui_operationalScreen);
    lv_obj_set_width(ui_levelColourIndicator, 245);
    lv_obj_set_height(ui_levelColourIndicator, 50);
    lv_obj_set_x(ui_levelColourIndicator, 1);
    lv_obj_set_y(ui_levelColourIndicator, 23);
    lv_obj_set_align(ui_levelColourIndicator, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_levelColourIndicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_levelColourIndicator, lv_color_hex(0x05820A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_levelColourIndicator, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_levelColourIndicator, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_levelColourIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_operationalScreen);
    lv_obj_set_width(ui_Panel1, 253);
    lv_obj_set_height(ui_Panel1, 55);
    lv_obj_set_x(ui_Panel1, -2);
    lv_obj_set_y(ui_Panel1, 131);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0xD4CA00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Panel1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cardRemaining = lv_label_create(ui_operationalScreen);
    lv_obj_set_width(ui_cardRemaining, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cardRemaining, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cardRemaining, 0);
    lv_obj_set_y(ui_cardRemaining, 23);
    lv_obj_set_align(ui_cardRemaining, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cardRemaining, "1000 L");
    lv_obj_set_style_text_color(ui_cardRemaining, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cardRemaining, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cardRemaining, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ledIndicator = lv_obj_create(ui_operationalScreen);
    lv_obj_set_width(ui_ledIndicator, 31);
    lv_obj_set_height(ui_ledIndicator, 29);
    lv_obj_set_x(ui_ledIndicator, -5);
    lv_obj_set_y(ui_ledIndicator, -85);
    lv_obj_set_align(ui_ledIndicator, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ledIndicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ledIndicator, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ledIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_operationalScreen);
    lv_image_set_src(ui_Image1, &ui_img_mifaretag_gra_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, -6);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Panel2 = lv_obj_create(ui_operationalScreen);
    lv_obj_set_width(ui_Panel2, 289);
    lv_obj_set_height(ui_Panel2, 44);
    lv_obj_set_x(ui_Panel2, 7);
    lv_obj_set_y(ui_Panel2, -138);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0xD5CA00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Panel2, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_flowRateSensor = lv_label_create(ui_operationalScreen);
    lv_obj_set_width(ui_flowRateSensor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_flowRateSensor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_flowRateSensor, -90);
    lv_obj_set_y(ui_flowRateSensor, 133);
    lv_obj_set_align(ui_flowRateSensor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_flowRateSensor, "67");
    lv_obj_add_flag(ui_flowRateSensor, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_flowRateSensor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_flowRateSensor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_flowRateSensor, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonState = lv_label_create(ui_operationalScreen);
    lv_obj_set_width(ui_buttonState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_buttonState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_buttonState, 55);
    lv_obj_set_y(ui_buttonState, -134);
    lv_obj_set_align(ui_buttonState, LV_ALIGN_CENTER);
    lv_label_set_text(ui_buttonState, "HIGH");
    lv_obj_add_flag(ui_buttonState, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_buttonState, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_buttonState, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_buttonState, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_customerID = lv_label_create(ui_operationalScreen);
    lv_obj_set_width(ui_customerID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_customerID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_customerID, 0);
    lv_obj_set_y(ui_customerID, -138);
    lv_obj_set_align(ui_customerID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_customerID, "07970242024");
    lv_obj_set_style_text_color(ui_customerID, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_customerID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_customerID, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cardErrorStatus = lv_label_create(ui_operationalScreen);
    lv_obj_set_width(ui_cardErrorStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cardErrorStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cardErrorStatus, 0);
    lv_obj_set_y(ui_cardErrorStatus, 130);
    lv_obj_set_align(ui_cardErrorStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cardErrorStatus, "No Card");
    lv_obj_set_style_text_color(ui_cardErrorStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cardErrorStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cardErrorStatus, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_totalRemainingBar = ui_totalRemainingBar;
    uic_levelColourIndicator = ui_levelColourIndicator;
    uic_cardRemaining = ui_cardRemaining;
    uic_ledIndicator = ui_ledIndicator;
    uic_flowRateSensor = ui_flowRateSensor;
    uic_buttonState = ui_buttonState;
    uic_customerID = ui_customerID;
    uic_cardErrorStatus = ui_cardErrorStatus;

}

void ui_operationalScreen_screen_destroy(void)
{
    if(ui_operationalScreen) lv_obj_del(ui_operationalScreen);

    // NULL screen variables
    ui_operationalScreen = NULL;
    uic_totalRemainingBar = NULL;
    ui_totalRemainingBar = NULL;
    uic_levelColourIndicator = NULL;
    ui_levelColourIndicator = NULL;
    ui_Panel1 = NULL;
    uic_cardRemaining = NULL;
    ui_cardRemaining = NULL;
    uic_ledIndicator = NULL;
    ui_ledIndicator = NULL;
    ui_Image1 = NULL;
    ui_Panel2 = NULL;
    uic_flowRateSensor = NULL;
    ui_flowRateSensor = NULL;
    uic_buttonState = NULL;
    ui_buttonState = NULL;
    uic_customerID = NULL;
    ui_customerID = NULL;
    uic_cardErrorStatus = NULL;
    ui_cardErrorStatus = NULL;

}
