/*
 * @attention
 * Copyright (c) Sevantica 2025.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#ifndef APPLICATION_INCLUDE_FIRMWARE_VERSION_H_
#define APPLICATION_INCLUDE_FIRMWARE_VERSION_H_

/*Includes ----------------------------------------------------------*/
#include <stdint.h>

/*Defines ------------------------------------------------------------*/

/* Firmware Version Information */
#define FW_VERSION_MAJOR    1
#define FW_VERSION_MINOR    2
#define FW_VERSION_PATCH    37
#define FW_BUILD_NUMBER     1

/* Build Date/Time (auto-generated by compiler) */
#define FW_BUILD_DATE       __DATE__
#define FW_BUILD_TIME       __TIME__

/* Project Name */
#define FW_PROJECT_NAME     "MyWota"

/* Bootloader Compatibility */
#define FW_MIN_BOOTLOADER_VERSION  "1.0.0"

/*Function Prototypes ------------------------------------------------*/

/**
 * @brief Get firmware version string (e.g., "1.0.0.1")
 * @return const char* Version string
 */
const char* FW_GetVersionString(void);

/**
 * @brief Get build date string (e.g., "Jan 10 2026")
 * @return const char* Build date
 */
const char* FW_GetBuildDateString(void);

/**
 * @brief Get build time string (e.g., "14:23:45")
 * @return const char* Build time
 */
const char* FW_GetBuildTimeString(void);

/**
 * @brief Get firmware version as 32-bit number
 * @return uint32_t Version (Major.Minor.Patch.Build packed)
 */
uint32_t FW_GetVersionNumber(void);

/**
 * @brief Print full firmware version information to USB log
 */
void FW_PrintVersionInfo(void);

#endif /* APPLICATION_INCLUDE_FIRMWARE_VERSION_H_ */
